# Generated by Django 4.1.3 on 2022-11-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('author', models.CharField(max_length=25)),
                ('publisher', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
