# Generated by Django 4.1.3 on 2022-11-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookModels',
            new_name='BookModel',
        ),
    ]
